#ifndef __BIND_GEN__
#define __BIND_GEN__

/* Generated with cbindgen:0.29.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum YaildEndpointMethod {
  Get = 0,
  Post = 1,
  Put = 2,
  Delete = 3,
} YaildEndpointMethod;

typedef enum YaildEndpointParamKind {
  Body = 0,
  Path = 1,
  Query = 2,
  Unknown = 255,
} YaildEndpointParamKind;

typedef enum YaildUnionKind {
  Untagged = 0,
  Interal = 1,
  External = 2,
} YaildUnionKind;

/**
 * `T[n]` or `T[]` wrapper.
 */
typedef struct ArrayType ArrayType;

/**
 * Tiny tree-based code builder that preserves indentation.
 */
typedef struct Code Code;

/**
 * Aggregates all parsed type and endpoint declarations.
 */
typedef struct Definitons Definitons;

/**
 * Semantic representation of a declared endpoint.
 */
typedef struct EndPoint EndPoint;

typedef struct EndpointParamWrapper EndpointParamWrapper;

/**
 * Representation coercion, e.g. `string as datetime`.
 */
typedef struct IntoType IntoType;

typedef struct MapType MapType;

/**
 * `T?` wrapper.
 */
typedef struct OptionType OptionType;

/**
 * Primitive scalars available in the DSL.
 */
typedef struct PrimitiveType PrimitiveType;

/**
 * Transport representations available to `IntoType`.
 */
typedef struct Repr Repr;

typedef struct String String;

typedef struct StructMemberWrapper StructMemberWrapper;

/**
 * Struct-like layout (`type Foo = { bar: Baz }`).
 */
typedef struct StructType StructType;

/**
 * Root semantic type tree used by generators.
 */
typedef struct Type Type;

/**
 * Metadata for a single named type in the DSL.
 */
typedef struct TypeInformation TypeInformation;

typedef struct UnionMember UnionMember;

/**
 * Wrapper describing `T1 | T2 | ... | Tn` and how it is tagged.
 */
typedef struct UnionType UnionType;

typedef enum CodeFFI_Tag {
  CodeBox,
  CodeRef,
} CodeFFI_Tag;

typedef struct CodeFFI {
  CodeFFI_Tag tag;
  union {
    struct {
      struct Code *code_box;
    };
    struct {
      struct Code *code_ref;
    };
  };
} CodeFFI;

/**
 * Wrapper around the full `Definitons` map for FFI consumers.
 */
typedef struct DefinitionsWrapper {
  const struct Definitons *defs;
} DefinitionsWrapper;

/**
 * Signature for callbacks that emit type headers (imports, etc).
 */
typedef struct CodeFFI (*TypeHeaderSign)(const void*,
                                         struct DefinitionsWrapper);

/**
 * Signature for callbacks that emit endpoint headers.
 */
typedef struct CodeFFI (*EndpointHeaderSign)(const void*,
                                             struct DefinitionsWrapper);

/**
 * Exposes `Type` to foreign code without leaking Rust's layout.
 */
typedef struct TypeWrapper {
  const struct Type *defs;
} TypeWrapper;

/**
 * Signature for callbacks that emit type definitions.
 */
typedef struct CodeFFI (*TypeSign)(const void*,
                                   const char*,
                                   struct TypeWrapper,
                                   char,
                                   struct DefinitionsWrapper);

/**
 * Wrapper around `TypeInformation` for FFI boundaries.
 */
typedef struct TypeInfoWrapper {
  const struct TypeInformation *defs;
} TypeInfoWrapper;

/**
 * Signature for callbacks that emit domain <-> wire translation helpers.
 */
typedef struct CodeFFI (*TypeTranslationSign)(const void*,
                                              char,
                                              struct TypeInfoWrapper,
                                              struct DefinitionsWrapper);

/**
 * Wrapper around `EndPoint` for FFI boundaries.
 */
typedef struct EndpointWrapper {
  const struct EndPoint *defs;
} EndpointWrapper;

/**
 * Signature for callbacks that emit endpoint functions.
 */
typedef struct CodeFFI (*EndpointSign)(const void*,
                                       const char*,
                                       struct EndpointWrapper,
                                       struct DefinitionsWrapper);

/**
 * Trait object adapter that lets native generators be exposed via FFI.
 */
typedef struct GeneratorFFI {
  /**
   * Opaque foreign context pointer forwarded to every callback.
   */
  const void *this_;
  TypeHeaderSign header_type;
  EndpointHeaderSign header_endpoint;
  TypeSign ty;
  TypeTranslationSign wire_translation;
  TypeTranslationSign domain_translation;
  EndpointSign endpoint;
} GeneratorFFI;

typedef struct ArrayWrapper {
  const struct ArrayType *_0;
} ArrayWrapper;

typedef struct IntoWrapper {
  const struct IntoType *_0;
} IntoWrapper;

typedef struct ReprWrapper {
  const struct Repr *_0;
} ReprWrapper;

typedef struct PrimitiveWrapper {
  const struct PrimitiveType *_0;
} PrimitiveWrapper;

typedef struct MapWrapper {
  const struct MapType *_0;
} MapWrapper;

typedef struct YaildStringView {
  const char *ptr;
  size_t len;
} YaildStringView;

typedef struct NamedWrapper {
  const struct String *_0;
} NamedWrapper;

typedef struct OptionalWrapper {
  const struct OptionType *_0;
} OptionalWrapper;

typedef struct StructWrapper {
  const struct StructType *_0;
} StructWrapper;

typedef struct UndeterminedWrapper {
  const struct String *_0;
} UndeterminedWrapper;

typedef struct UnionWrapper {
  const struct UnionType *_0;
} UnionWrapper;

typedef struct UnionMemberWrapper {
  const struct UnionMember *_0;
} UnionMemberWrapper;

void yaidl_code_add_child(struct CodeFFI *self,
                          struct CodeFFI code);

void yaidl_code_add_line(struct CodeFFI *self,
                         const char *line);

struct CodeFFI yaidl_code_create_child_block(struct CodeFFI *self);

struct CodeFFI yaidl_code_create_child_segment(struct CodeFFI *self);

struct CodeFFI yaidl_code_new_block(void);

struct CodeFFI yaidl_code_new_line(const char *line);

struct CodeFFI yaidl_code_new_segment(void);

struct GeneratorFFI yaidl_generator_new(void);

struct GeneratorFFI yaidl_generator_set_domain_translation(struct GeneratorFFI self,
                                                           TypeTranslationSign t);

struct GeneratorFFI yaidl_generator_set_endpoint(struct GeneratorFFI self,
                                                 EndpointSign t);

struct GeneratorFFI yaidl_generator_set_header_endpoint(struct GeneratorFFI self,
                                                        EndpointHeaderSign t);

struct GeneratorFFI yaidl_generator_set_header_type(struct GeneratorFFI self,
                                                    TypeHeaderSign t);

struct GeneratorFFI yaidl_generator_set_this(struct GeneratorFFI self,
                                             const void *t);

struct GeneratorFFI yaidl_generator_set_type(struct GeneratorFFI self,
                                             TypeSign t);

struct GeneratorFFI yaidl_generator_set_wire_translation(struct GeneratorFFI self,
                                                         TypeTranslationSign t);

size_t yaild_array_get_len(const struct ArrayWrapper *wrapper);

struct TypeWrapper yaild_array_get_type(const struct ArrayWrapper *wrapper);

bool yaild_array_has_len(const struct ArrayWrapper *wrapper);

bool yaild_definitions_has_endpoint(const struct DefinitionsWrapper *wrapper,
                                    const char *name);

bool yaild_definitions_has_named_type(const struct DefinitionsWrapper *wrapper,
                                      const char *name);

struct TypeWrapper yaild_into_get_from(const struct IntoWrapper *wrapper);

struct ReprWrapper yaild_into_get_repr(const struct IntoWrapper *wrapper);

struct PrimitiveWrapper yaild_map_get_key(const struct MapWrapper *wrapper);

struct TypeWrapper yaild_map_get_value(const struct MapWrapper *wrapper);

struct YaildStringView yaild_named_get_value(const struct NamedWrapper *wrapper);

struct TypeWrapper yaild_optional_get_type(const struct OptionalWrapper *wrapper);

bool yaild_repr_is_datetime(const struct ReprWrapper *wrapper);

struct StructMemberWrapper yaild_struct_get_member(const struct StructWrapper *wrapper,
                                                   size_t index);

size_t yaild_struct_get_member_len(const struct StructWrapper *wrapper);

struct YaildStringView yaild_struct_member_get_name(const struct StructMemberWrapper *wrapper);

struct TypeWrapper yaild_struct_member_get_type(const struct StructMemberWrapper *wrapper);

bool yaild_typeinfo_has_conversion(const struct TypeInfoWrapper *wrapper);

bool yaild_typeinfo_has_name(const struct TypeInfoWrapper *wrapper);

struct YaildStringView yaild_undetermined_get_value(const struct UndeterminedWrapper *wrapper);

enum YaildUnionKind yaild_union_get_kind(const struct UnionWrapper *wrapper);

struct UnionMemberWrapper yaild_union_get_member(const struct UnionWrapper *wrapper,
                                                 size_t index);

size_t yaild_union_get_member_len(const struct UnionWrapper *wrapper);

struct YaildStringView yaild_union_member_get_tag(const struct UnionMemberWrapper *wrapper);

struct TypeWrapper yaild_union_member_get_type(const struct UnionMemberWrapper *wrapper);

bool yaild_union_member_has_tag(const struct UnionMemberWrapper *wrapper);

struct EndpointWrapper yailde_definitions_get_endpoint(const struct DefinitionsWrapper *wrapper,
                                                       const char *name);

struct TypeInfoWrapper yailde_definitions_get_named_type(const struct DefinitionsWrapper *wrapper,
                                                         const char *name);

enum YaildEndpointMethod yailde_endpoint_get_method(const struct EndpointWrapper *wrapper);

struct YaildStringView yailde_endpoint_get_method_name(const struct EndpointWrapper *wrapper);

struct EndpointParamWrapper yailde_endpoint_get_param(const struct EndpointWrapper *wrapper,
                                                      size_t index);

size_t yailde_endpoint_get_param_len(const struct EndpointWrapper *wrapper);

struct TypeWrapper yailde_endpoint_get_return_type(const struct EndpointWrapper *wrapper);

struct YaildStringView yailde_endpoint_get_url(const struct EndpointWrapper *wrapper);

enum YaildEndpointParamKind yailde_endpoint_param_get_kind(const struct EndpointWrapper *endpoint,
                                                           const struct EndpointParamWrapper *wrapper);

struct YaildStringView yailde_endpoint_param_get_name(const struct EndpointParamWrapper *wrapper);

struct TypeWrapper yailde_endpoint_param_get_type(const struct EndpointParamWrapper *wrapper);

size_t yailde_typeinfo_get_col(const struct TypeInfoWrapper *wrapper);

struct TypeWrapper yailde_typeinfo_get_domain_type(const struct TypeInfoWrapper *wrapper);

size_t yailde_typeinfo_get_line(const struct TypeInfoWrapper *wrapper);

struct YaildStringView yailde_typeinfo_get_name(const struct TypeInfoWrapper *wrapper);

struct YaildStringView yailde_typeinfo_get_path(const struct TypeInfoWrapper *wrapper);

struct TypeWrapper yailde_typeinfo_get_type(const struct TypeInfoWrapper *wrapper);

struct YaildStringView yailde_typeinfo_get_wire_name(const struct TypeInfoWrapper *wrapper);

struct TypeWrapper yailde_typeinfo_get_wire_type(const struct TypeInfoWrapper *wrapper);

#endif  /* __BIND_GEN__ */
